/* Automatically generated by './build/bin/build-entry.js' */

import Table from "./table/index.js";

const components = [Table];

const install = function(Vue, opts = {}) {
	components.forEach(component => {
		Vue.component(component.name, component);
	});
};

/* istanbul ignore if */
if (typeof window !== "undefined" && window.Vue) {
	install(window.Vue);
}

export default {
	Table: Table
};
